const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permissions: state => state.user.permissions,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  language: state => state.app.language,
	size: state => state.app.size,
  stackRoutes: state => state.permission.stackRoute,
  showService: state => state.settings.showBindeService,
  serveiceList: state => state.settings.serviceList,
  codeCurrencyList: state => state.code.currencyList,
  counterList: state => state.code.counterList,
  selectTime: state => state.code.selectTime,
  codeNum: state => state.code.codeNum,
  codeDes: state => state.code.codeDes
}
export default getters
